// <auto-generated />
namespace WorkoutPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedforeginkeytoexercisetableremovedforeignkeyfromworkouttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedforeginkeytoexercisetableremovedforeignkeyfromworkouttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201704071454422_added foreginkey to exercise table, removed foreignkey from workout table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
