// <auto-generated />
namespace WorkoutPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedcolumnsforuserinfotable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedcolumnsforuserinfotable));
        
        string IMigrationMetadata.Id
        {
            get { return "201704172127087_changed columns for userinfo table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
