// <auto-generated />
namespace WorkoutPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedmuscleandexercisetables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmuscleandexercisetables));
        
        string IMigrationMetadata.Id
        {
            get { return "201704062104535_added muscle and exercise tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
