//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventfulz
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartAt { get; set; }
        public System.DateTime EndAt { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
        public string userEmail { get; set; }
    }
}
